In [0]:
import torch

In [0]:
def matmul(a,b):
    ar,ac = a.shape # n_rows * n_cols
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): # or br
                c[i,j] += a[i,k] * b[k,j]
    return c

In [0]:
weights = torch.randn(784,10)
bias = torch.zeros(10)
x = torch.randn(5, 784)

In [12]:
x.shape,weights.shape

(torch.Size([5, 784]), torch.Size([784, 10]))

In [14]:
%time t1=matmul(x, weights)

CPU times: user 851 ms, sys: 0 ns, total: 851 ms
Wall time: 888 ms


In [16]:
t1.shape

torch.Size([5, 10])

In [17]:
a = tensor([10., 6, -4])
b = tensor([2., 8, 7])
a,b

(tensor([10.,  6., -4.]), tensor([2., 8., 7.]))

In [20]:
(a > 0).float().mean()

tensor(0.6667)

Frobenius norm:

$$\| A \|_F = \left( \sum_{i,j=1}^n | a_{ij} |^2 \right)^{1/2}$$

*Hint*: you don't normally need to write equations in LaTeX yourself, instead, you can click 'edit' in Wikipedia and copy the LaTeX from there (which is what I did for the above equation). Or on arxiv.org, click "Download: Other formats" in the top right, then "Download source"; rename the downloaded file to end in `.tgz` if it doesn't already, and you should find the source there, including the equations to copy and paste.


In [23]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]]); m

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [26]:
(m * m).sum().sqrt()

tensor(16.8819)

In [0]:
# elementwise multiplication
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            # Any trailing ",:" can be removed
            c[i,j] = (a[i,:] * b[:,j]).sum()
    return c

In [31]:
a > 0

tensor([ True,  True, False])

In [34]:
a.view(3, 1)

tensor([[10.],
        [ 6.],
        [-4.]])

In [35]:
a > 0

tensor([ True,  True, False])

In [36]:
c = tensor([10.,20,30]); c

tensor([10., 20., 30.])

In [38]:
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3]))

In [39]:
m + c

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [40]:
t = c.expand_as(m); t

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [41]:
t.storage()

 10.0
 20.0
 30.0
[torch.FloatStorage of size 3]

In [42]:
t.stride(), t.shape

((0, 1), torch.Size([3, 3]))

In [43]:
c.unsqueeze(0)

tensor([[10., 20., 30.]])

In [44]:
c.unsqueeze(1)

tensor([[10.],
        [20.],
        [30.]])

In [45]:
c.shape, c.unsqueeze(0).shape,c.unsqueeze(1).shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [46]:
c.shape, c[None].shape,c[:,None].shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [0]:
# matmul with broadcasting
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
#       c[i,j] = (a[i,:]          * b[:,j]).sum() # previous
        c[i]   = (a[i  ].unsqueeze(-1) * b).sum(dim=0)
    return c

In [49]:
c[None,:], c[:,None]

(tensor([[10., 20., 30.]]), tensor([[10.],
         [20.],
         [30.]]))

In [50]:
c[None,:] * c[:,None]

tensor([[100., 200., 300.],
        [200., 400., 600.],
        [300., 600., 900.]])

In [51]:
c[None] > c[:,None], c[:, None] > c[None]

(tensor([[False,  True,  True],
         [False, False,  True],
         [False, False, False]]), tensor([[False, False, False],
         [ True, False, False],
         [ True,  True, False]]))